apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-turrets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turret
  template:
    metadata:
      labels:
        app: turret
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: turret-service
spec:
  selector:
    app: turret
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
